#if !defined(META_BENCH_REGEXES_H)
#define META_BENCH_REGEXES_H

#include "meta.h"

enum BenchRegexLengthClass {
    BENCH_LEN_1_8,
    BENCH_LEN_9_16,
    BENCH_LEN_17_32,
    BENCH_LEN_33_64,
    BENCH_LEN_LAST,
};

typedef struct BenchRegexCase {
    MetaRegex *regex;
    int32 regex_len;
    enum BenchRegexLengthClass length_class;
} BenchRegexCase;

typedef struct BenchRegexBucket {
    char *name;
    enum BenchRegexLengthClass length_class;
    int32 is_backref;
    int32 max_regex_len;
    BenchRegexCase *cases;
    int32 count;
} BenchRegexBucket;

static char *
bench_length_class_name(enum BenchRegexLengthClass c) {
    switch (c) {
    case BENCH_LEN_1_8: return "1_8";
    case BENCH_LEN_9_16: return "9_16";
    case BENCH_LEN_17_32: return "17_32";
    case BENCH_LEN_33_64: return "33_64";
    case BENCH_LEN_LAST:
    default: return "unknown_length";
    }
}

static int32
bench_length_class_max(enum BenchRegexLengthClass c) {
    switch (c) {
    case BENCH_LEN_1_8: return 8;
    case BENCH_LEN_9_16: return 16;
    case BENCH_LEN_17_32: return 32;
    case BENCH_LEN_33_64: return 64;
    case BENCH_LEN_LAST:
    default: return 0;
    }
}

static BenchRegexCase bench_regex_cases[] = {
    { R("a") },
    { R("z") },
    { R("0") },
    { R("foo") },
    { R("bar") },
    { R("baz") },
    { R("qux") },
    { R("zip") },
    { R("zap") },
    { R("abc") },
    { R("a.c") },
    { R("f.o") },
    { R("x.y") },
    { R("ab[cd]") },
    { R("x[0-9]z") },
    { R("[a-z]") },
    { R("[0-9]") },
    { R("[a-z0-9]") },
    { R("[_a-z]") },
    { R("[-_a-z]") },
    { R("[^0-9]") },
    { R("[^ ]") },
    { R("[[:digit:]]") },
    { R("[[:alpha:]]") },
    { R("[[:alnum:]]") },
    { R("[[:space:]]") },
    { R("[[:punct:]]") },
    { R("[[:xdigit:]]") },
    { R("[[:lower:]]") },
    { R("[[:blank:]]") },
    { R("a?") },
    { R("a*") },
    { R("a+") },
    { R("a{1}") },
    { R("a{2}") },
    { R("a{3}") },
    { R("a{1,2}") },
    { R("a{2,4}") },
    { R("a{0,3}") },
    { R("a{3,5}") },
    { R("b?") },
    { R("b*") },
    { R("b+") },
    { R("b{1}") },
    { R("b{2}") },
    { R("b{3}") },
    { R("b{1,2}") },
    { R("b{2,4}") },
    { R("b{0,3}") },
    { R("b{3,5}") },
    { R("x?") },
    { R("x*") },
    { R("x+") },
    { R("x{1}") },
    { R("x{2}") },
    { R("x{3}") },
    { R("x{1,2}") },
    { R("x{2,4}") },
    { R("x{0,3}") },
    { R("x{3,5}") },
    { R("[a-z]?") },
    { R("[a-z]*") },
    { R("[a-z]+") },
    { R("[a-z]{1}") },
    { R("[a-z]{2}") },
    { R("[a-z]{3}") },
    { R("[a-z]{1,2}") },
    { R("[a-z]{2,4}") },
    { R("[a-z]{0,3}") },
    { R("[a-z]{3,5}") },
    { R("ab?c") },
    { R("ab*c") },
    { R("ab+c") },
    { R("a[0-9]?b") },
    { R("a[0-9]*b") },
    { R("a[0-9]+b") },
    { R("[a-z]+[0-9]+") },
    { R("[0-9]+[a-z]+") },
    { R("[a-z]{2}[0-9]{2}") },
    { R("[a-z]{1,3}_[0-9]{1,3}") },
    { R("foo[0-9]*") },
    { R("bar[a-z]+") },
    { R("baz[_-]?[0-9]+") },
    { R("qux[[:space:]]+zap") },
    { R("[[:alpha:]]+[[:space:]][[:digit:]]+") },
    { R("[[:alnum:]]{3,8}") },
    { R("x[a-z]{2,5}y") },
    { R("a.{1,3}z") },
    { R("[^ ]+[[:space:]]+end") },
    { R("[a-f0-9]{2}:[a-f0-9]{2}") },
    { R("[a-z]+\\.[a-z]{2,4}") },
    { R("[a-z]+@[a-z]+\\.[a-z]{2,4}") },
    { R("[0-9]{4}-[0-9]{2}-[0-9]{2}") },
    { R("[0-9]{2}/[0-9]{2}/[0-9]{4}") },
    { R("[a-z]{3}_[a-z]{3}_[0-9]{2}") },
    { R("[a-z0-9._-]+") },
    { R("[[:punct:]]+[a-z]?") },
    { R("(foo|bar)") },
    { R("(baz|qux)") },
    { R("(zip|zap)") },
    { R("(cat|dog)") },
    { R("(red|blue)") },
    { R("(one|two)") },
    { R("(foo|bar|baz)") },
    { R("(qux|zip|zap)") },
    { R("(cat|dog|red)") },
    { R("(blue|one|two)") },
    { R("(foo|bar)[0-9]?") },
    { R("(foo|bar)[0-9]+") },
    { R("(foo|bar|baz)[a-z]*") },
    { R("([a-z]|[0-9])+") },
    { R("([a-z]{2}|[0-9]{2})+") },
    { R("(ab|cd|ef){1,3}") },
    { R("(foo|[0-9]{2})") },
    { R("(bar|[a-z]{3})") },
    { R("([[:alpha:]]+|[[:digit:]]+)") },
    { R("(a|ab|abc)") },
    { R("(abc|ab|a)") },
    { R("x(foo|bar)y") },
    { R("(pre)?fix") },
    { R("un(do|done)?") },
    { R("(ha)+") },
    { R("(ab)*c") },
    { R("a(bc)+d") },
    { R("a(b|c|d)c") },
    { R("(xy|z)*end") },
    { R("([a-z]+)_([0-9]+)") },
    { R("([0-9]{2})-([a-z]{2})") },
    { R("n(e(s)t)ed") },
    { R("([a-z])([0-9])") },
    { R("([[:alpha:]])([[:digit:]])") },
    { R("(foo) (bar)") },
    { R("(a|b)(c|d)(e|f)") },
    { R("(red|blue)[_-](cat|dog)") },
    { R("([a-z]{2}|[0-9]{3})[-_](x|y)?") },
    { R("(foo|bar)+(baz|qux)?") },
    { R("([[:lower:]]{2,4}|[[:digit:]]{1,3})") },
    { R("^foo") },
    { R("bar$") },
    { R("^foo$") },
    { R("^[a-z]+$") },
    { R("^[0-9]+$") },
    { R("^[a-z0-9_]+$") },
    { R("^foo[0-9]*$") },
    { R("^bar[a-z]+$") },
    { R("^baz[_-]?[0-9]+$") },
    { R("^[[:space:]]*[a-z]+[[:space:]]*$") },
    { R("^[[:digit:]]{2,4}$") },
    { R("^([a-z]+|[0-9]+)$") },
    { R("^(foo|bar|baz)$") },
    { R("^a(b|c)*d$") },
    { R("^[a-z]{2,4}-[0-9]{1,3}$") },
    { R("^[^ ]+[[:space:]]+[^ ]+$") },
    { R("^([0-9]{4})-([0-9]{2})-([0-9]{2})$") },
    { R("^[a-z]+\\.[a-z]{2,4}$") },
    { R("^([a-z]+)@([a-z]+)\\.([a-z]{2,4})$") },
    { R("^.{1,16}$") },
    { R("^[[:punct:]]+$") },
    { R("^[[:xdigit:]]{2}(:[[:xdigit:]]{2})*$") },
    { R("\\bfoo\\b") },
    { R("\\bbar\\b") },
    { R("\\bbaz[0-9]?\\b") },
    { R("\\b[a-z]+\\b") },
    { R("\\b[0-9]+\\b") },
    { R("\\Baa") },
    { R("aa\\B") },
    { R("\\B[a-z]{2}\\B") },
    { R("\\B[0-9]+\\B") },
    { R("\\<foo\\>") },
    { R("\\<bar[0-9]?\\>") },
    { R("\\<[a-z]+\\>") },
    { R("\\<[0-9]+\\>") },
    { R("\\<([a-z]{2}|[0-9]{2})\\>") },
    { R("\\b(foo|bar)\\b") },
    { R("\\b(foo|bar)[0-9]*\\b") },
    { R("\\B(foo|bar)\\B") },
    { R("\\<[[:alpha:]]+[[:digit:]]?\\>") },
    { R("\\b[a-z]+_[0-9]+\\b") },
    { R("\\B[a-z]{2,5}[0-9]?\\B") },
    { R("\\<(pre|post)[a-z]*\\>") },
    { R("\\b(cat|dog)s?\\b") },
    { R("\\b[[:alnum:]_]+\\b") },
    { R("\\B[_-][a-z]+\\B") },
    { R("\\<[a-z]{1,3}(-[a-z]{1,3})?\\>") },
    { R("pre[-_]?[a-z]{1,4}[-_]?id[0-9]?") },
    { R("pre[-_]?[a-z]{1,4}[-_]?key[0-9]?") },
    { R("pre[-_]?[a-z]{1,4}[-_]?val[0-9]?") },
    { R("pre[-_]?[a-z]{1,4}[-_]?num[0-9]?") },
    { R("pre[-_]?[a-z]{1,4}[-_]?tag[0-9]?") },
    { R("pre[-_]?[a-z]{1,4}[-_]?ref[0-9]?") },
    { R("pre[-_]?[a-z]{1,4}[-_]?log[0-9]?") },
    { R("pre[-_]?[a-z]{1,4}[-_]?cfg[0-9]?") },
    { R("pre[-_]?[a-z]{1,4}[-_]?bin[0-9]?") },
    { R("pre[-_]?[a-z]{1,4}[-_]?src[0-9]?") },
    { R("post[-_]?[a-z]{1,4}[-_]?id[0-9]?") },
    { R("post[-_]?[a-z]{1,4}[-_]?key[0-9]?") },
    { R("post[-_]?[a-z]{1,4}[-_]?val[0-9]?") },
    { R("post[-_]?[a-z]{1,4}[-_]?num[0-9]?") },
    { R("post[-_]?[a-z]{1,4}[-_]?tag[0-9]?") },
    { R("post[-_]?[a-z]{1,4}[-_]?ref[0-9]?") },
    { R("post[-_]?[a-z]{1,4}[-_]?log[0-9]?") },
    { R("post[-_]?[a-z]{1,4}[-_]?cfg[0-9]?") },
    { R("post[-_]?[a-z]{1,4}[-_]?bin[0-9]?") },
    { R("post[-_]?[a-z]{1,4}[-_]?src[0-9]?") },
    { R("mid[-_]?[a-z]{1,4}[-_]?id[0-9]?") },
    { R("mid[-_]?[a-z]{1,4}[-_]?key[0-9]?") },
    { R("mid[-_]?[a-z]{1,4}[-_]?val[0-9]?") },
    { R("mid[-_]?[a-z]{1,4}[-_]?num[0-9]?") },
    { R("mid[-_]?[a-z]{1,4}[-_]?tag[0-9]?") },
    { R("mid[-_]?[a-z]{1,4}[-_]?ref[0-9]?") },
    { R("([a-z]{1,3}\\.){1,3}[a-z]{2,4}") },
    { R("([0-9]{1,3}\\.){3}[0-9]{1,3}") },
    { R("([a-z]+/){1,4}[a-z0-9._-]+") },
    { R("/?([a-z]+/)*[a-z]+\\.[a-z]{1,4}") },
    { R("(http|https)://[a-z0-9._-]+(/[a-z0-9._-]+)*") },
    { R("[a-z]+://[a-z0-9._-]+(:[0-9]{2,5})?") },
    { R("([a-z]+:)?[0-9]{1,4}") },
    { R("[a-z]{2,5}:[0-9]{1,4}(:[a-z]+)?") },
    { R("([a-z]+,){1,4}[a-z]+") },
    { R("([0-9]+;){1,3}[0-9]+") },
    { R("\\[[a-z0-9_-]+\\]") },
    { R("\\{[a-z0-9_-]+\\}") },
    { R("\\([a-z0-9_-]+\\)") },
    { R("\\[[0-9]{1,3}\\][a-z]+") },
    { R("[a-z]+\\([0-9]{1,3}\\)") },
    { R("([a-z]{2}|[0-9]{2}|[_-]){2,8}") },
    { R("([[:lower:]]|[[:digit:]]|_)+") },
    { R("([[:alpha:]][[:alnum:]_]*)") },
    { R("([[:alpha:]][[:alnum:]_]*)([[:space:]]*=[[:space:]]*[[:alnum:]_]+)?") },
    { R("[[:space:]]*(foo|bar|baz)[[:space:]]*") },
    { R("[[:space:]]+|[[:punct:]]+") },
    { R("([a-z]+[[:space:]]){1,4}[a-z]+") },
    { R("([0-9]{2}:){2}[0-9]{2}") },
    { R("([0-9]{1,2}:)?[0-9]{2}:[0-9]{2}") },
    { R("([a-z]{3})?-[0-9]{2,4}") },
    { R("([a-z]{3}-)?[a-z]{3}-[0-9]{2}") },
    { R("([a-z]{1,3}|[0-9]{1,3})(-[a-z0-9]{1,3})*") },
    { R("([a-z]{2,4}\\+)?[a-z]{2,4}") },
    { R("([a-z]{1,4}\\*)?[0-9]{1,4}") },
    { R("([a-z]+\\.)?[a-z]+@[a-z]+\\.[a-z]{2,4}") },
    { R("\\<([a-z]+|[0-9]{2,4})(-[a-z]+)?\\>") },
    { R("\\b(foo|bar|baz)[[:space:]]+[0-9]+\\b") },
    { R("\\B([abc]{1,3}|[0-9]{1,2})+(end)?\\B") },
    { R("^([a-z]{2,4}|[0-9]{2,4})[-_][a-z0-9]{1,6}$") },
    { R("^[[:space:]]*(yes|no|true|false)[[:space:]]*$") },
    { R("^([a-z]+)(\\.[a-z]+){0,3}$") },
    { R("^([0-9]+)(\\.[0-9]+){0,3}$") },
    { R("\\b[a-z]{2,4}([_-][a-z0-9]{1,4}){0,3}\\b") },
    { R("\\<[a-z]+([[:space:]]+[a-z]+){0,3}\\>") },
    { R("([a-z]{1,3}\\|){1,3}[a-z]{1,3}") },
};

#define BENCH_REGEX_CASE_COUNT LENGTH(bench_regex_cases)

static BenchRegexCase bench_regex_backref_cases[] = {
    { R("([a-z])\\1") },
    { R("([0-9]+)\\1") },
    { R("(foo|bar)\\1") },
    { R("([a-z]{2})([0-9]{2})\\1\\2") },
    { R("^(a|b).*\\1$") },
    { R("([[:alpha:]])([[:digit:]])\\2\\1") },
};

#define BENCH_REGEX_BACKREF_CASE_COUNT LENGTH(bench_regex_backref_cases)

#endif /* META_BENCH_REGEXES_H */
