#if !defined(META_BENCH_REGEXES_H)
#define META_BENCH_REGEXES_H

#include "meta.h"

typedef enum BenchRegexLengthClass {
    BENCH_LEN_1_8,
    BENCH_LEN_9_16,
    BENCH_LEN_17_32,
    BENCH_LEN_33_64,
    BENCH_LEN_LAST,
} BenchRegexLengthClass;

typedef enum BenchRegexFeatureClass {
    BENCH_FEATURE_NO_BACKREFS,
    BENCH_FEATURE_ALL,
    BENCH_FEATURE_LAST,
} BenchRegexFeatureClass;

typedef struct BenchRegexCase {
    char *name;
    MetaRegex *regex;
    int32 regex_len;
    enum BenchRegexLengthClass length_class;
    enum BenchRegexFeatureClass feature_class;
} BenchRegexCase;

typedef struct BenchRegexBucket {
    char *name;
    enum BenchRegexLengthClass length_class;
    enum BenchRegexFeatureClass feature_class;
    int32 max_regex_len;
    BenchRegexCase *cases;
    int32 count;
} BenchRegexBucket;

static char *
bench_length_class_name(enum BenchRegexLengthClass c) {
    switch (c) {
    case BENCH_LEN_1_8: return "1_8";
    case BENCH_LEN_9_16: return "9_16";
    case BENCH_LEN_17_32: return "17_32";
    case BENCH_LEN_33_64: return "33_64";
    case BENCH_LEN_LAST:
    default: return "unknown_length";
    }
}

static int32
bench_length_class_max(enum BenchRegexLengthClass c) {
    switch (c) {
    case BENCH_LEN_1_8: return 8;
    case BENCH_LEN_9_16: return 16;
    case BENCH_LEN_17_32: return 32;
    case BENCH_LEN_33_64: return 64;
    case BENCH_LEN_LAST:
    default: return 0;
    }
}

static char *
bench_feature_class_name(enum BenchRegexFeatureClass c) {
    switch (c) {
    case BENCH_FEATURE_NO_BACKREFS:
        return "no_backreferences";
    case BENCH_FEATURE_ALL:
        return "with_backreferences";
    case BENCH_FEATURE_LAST:
    default:
        return "unknown_features";
    }
}

#define BENCH_REGEX_CASE_COUNT 500

static BenchRegexCase bench_regex_cases[BENCH_REGEX_CASE_COUNT] = {
    { "bench_re_0000", R("a0"), 0, BENCH_LEN_LAST, BENCH_FEATURE_LAST },
    { "bench_re_0001", R("[a-z]"), 0, BENCH_LEN_LAST, BENCH_FEATURE_LAST },
    { "bench_re_0002", R("[0-9]{3}"), 0, BENCH_LEN_LAST, BENCH_FEATURE_LAST },
    { "bench_re_0003", R("abd?"), 0, BENCH_LEN_LAST, BENCH_FEATURE_LAST },
    { "bench_re_0004", R("x[abc]4"), 0, BENCH_LEN_LAST, BENCH_FEATURE_LAST },
    { "bench_re_0005", R("a5"), 0, BENCH_LEN_LAST, BENCH_FEATURE_LAST },
    { "bench_re_0006", R("[a-z]+"), 0, BENCH_LEN_LAST, BENCH_FEATURE_LAST },
    { "bench_re_0007", R("[0-9]{2}"), 0, BENCH_LEN_LAST, BENCH_FEATURE_LAST },
    { "bench_re_0008", R("abi?"), 0, BENCH_LEN_LAST, BENCH_FEATURE_LAST },
    { "bench_re_0009", R("x[abc]9"), 0, BENCH_LEN_LAST, BENCH_FEATURE_LAST },
    { "bench_re_0010", R("a0"), 0, BENCH_LEN_LAST, BENCH_FEATURE_LAST },
    { "bench_re_0011", R("[a-z]"), 0, BENCH_LEN_LAST, BENCH_FEATURE_LAST },
    { "bench_re_0012", R("[0-9]{1}"), 0, BENCH_LEN_LAST, BENCH_FEATURE_LAST },
    { "bench_re_0013", R("abn?"), 0, BENCH_LEN_LAST, BENCH_FEATURE_LAST },
    { "bench_re_0014", R("x[abc]4"), 0, BENCH_LEN_LAST, BENCH_FEATURE_LAST },
    { "bench_re_0015", R("a5"), 0, BENCH_LEN_LAST, BENCH_FEATURE_LAST },
    { "bench_re_0016", R("[a-z]"), 0, BENCH_LEN_LAST, BENCH_FEATURE_LAST },
    { "bench_re_0017", R("[0-9]{3}"), 0, BENCH_LEN_LAST, BENCH_FEATURE_LAST },
    { "bench_re_0018", R("abs?"), 0, BENCH_LEN_LAST, BENCH_FEATURE_LAST },
    { "bench_re_0019", R("x[abc]9"), 0, BENCH_LEN_LAST, BENCH_FEATURE_LAST },
    { "bench_re_0020", R("a0"), 0, BENCH_LEN_LAST, BENCH_FEATURE_LAST },
    { "bench_re_0021", R("[a-z]+"), 0, BENCH_LEN_LAST, BENCH_FEATURE_LAST },
    { "bench_re_0022", R("[0-9]{2}"), 0, BENCH_LEN_LAST, BENCH_FEATURE_LAST },
    { "bench_re_0023", R("abx?"), 0, BENCH_LEN_LAST, BENCH_FEATURE_LAST },
    { "bench_re_0024", R("x[abc]4"), 0, BENCH_LEN_LAST, BENCH_FEATURE_LAST },
    { "bench_re_0025", R("a5"), 0, BENCH_LEN_LAST, BENCH_FEATURE_LAST },
    { "bench_re_0026", R("[a-z]"), 0, BENCH_LEN_LAST, BENCH_FEATURE_LAST },
    { "bench_re_0027", R("[0-9]{1}"), 0, BENCH_LEN_LAST, BENCH_FEATURE_LAST },
    { "bench_re_0028", R("abc?"), 0, BENCH_LEN_LAST, BENCH_FEATURE_LAST },
    { "bench_re_0029", R("x[abc]9"), 0, BENCH_LEN_LAST, BENCH_FEATURE_LAST },
    { "bench_re_0030", R("a0"), 0, BENCH_LEN_LAST, BENCH_FEATURE_LAST },
    { "bench_re_0031", R("[a-z]"), 0, BENCH_LEN_LAST, BENCH_FEATURE_LAST },
    { "bench_re_0032", R("[0-9]{3}"), 0, BENCH_LEN_LAST, BENCH_FEATURE_LAST },
    { "bench_re_0033", R("abh?"), 0, BENCH_LEN_LAST, BENCH_FEATURE_LAST },
    { "bench_re_0034", R("x[abc]4"), 0, BENCH_LEN_LAST, BENCH_FEATURE_LAST },
    { "bench_re_0035", R("a5"), 0, BENCH_LEN_LAST, BENCH_FEATURE_LAST },
    { "bench_re_0036", R("[a-z]+"), 0, BENCH_LEN_LAST, BENCH_FEATURE_LAST },
    { "bench_re_0037", R("[0-9]{2}"), 0, BENCH_LEN_LAST, BENCH_FEATURE_LAST },
    { "bench_re_0038", R("abm?"), 0, BENCH_LEN_LAST, BENCH_FEATURE_LAST },
    { "bench_re_0039", R("x[abc]9"), 0, BENCH_LEN_LAST, BENCH_FEATURE_LAST },
    { "bench_re_0040", R("a0"), 0, BENCH_LEN_LAST, BENCH_FEATURE_LAST },
    { "bench_re_0041", R("[a-z]"), 0, BENCH_LEN_LAST, BENCH_FEATURE_LAST },
    { "bench_re_0042", R("[0-9]{1}"), 0, BENCH_LEN_LAST, BENCH_FEATURE_LAST },
    { "bench_re_0043", R("abr?"), 0, BENCH_LEN_LAST, BENCH_FEATURE_LAST },
    { "bench_re_0044", R("x[abc]4"), 0, BENCH_LEN_LAST, BENCH_FEATURE_LAST },
    { "bench_re_0045", R("a5"), 0, BENCH_LEN_LAST, BENCH_FEATURE_LAST },
    { "bench_re_0046", R("[a-z]"), 0, BENCH_LEN_LAST, BENCH_FEATURE_LAST },
    { "bench_re_0047", R("[0-9]{3}"), 0, BENCH_LEN_LAST, BENCH_FEATURE_LAST },
    { "bench_re_0048", R("abw?"), 0, BENCH_LEN_LAST, BENCH_FEATURE_LAST },
    { "bench_re_0049", R("x[abc]9"), 0, BENCH_LEN_LAST, BENCH_FEATURE_LAST },
    { "bench_re_0050", R("a0"), 0, BENCH_LEN_LAST, BENCH_FEATURE_LAST },
    { "bench_re_0051", R("[a-z]+"), 0, BENCH_LEN_LAST, BENCH_FEATURE_LAST },
    { "bench_re_0052", R("[0-9]{2}"), 0, BENCH_LEN_LAST, BENCH_FEATURE_LAST },
    { "bench_re_0053", R("abb?"), 0, BENCH_LEN_LAST, BENCH_FEATURE_LAST },
    { "bench_re_0054", R("x[abc]4"), 0, BENCH_LEN_LAST, BENCH_FEATURE_LAST },
    { "bench_re_0055", R("a5"), 0, BENCH_LEN_LAST, BENCH_FEATURE_LAST },
    { "bench_re_0056", R("[a-z]"), 0, BENCH_LEN_LAST, BENCH_FEATURE_LAST },
    { "bench_re_0057", R("[0-9]{1}"), 0, BENCH_LEN_LAST, BENCH_FEATURE_LAST },
    { "bench_re_0058", R("abg?"), 0, BENCH_LEN_LAST, BENCH_FEATURE_LAST },
    { "bench_re_0059", R("x[abc]9"), 0, BENCH_LEN_LAST, BENCH_FEATURE_LAST },
    { "bench_re_0060", R("a0"), 0, BENCH_LEN_LAST, BENCH_FEATURE_LAST },
    { "bench_re_0061", R("[a-z]"), 0, BENCH_LEN_LAST, BENCH_FEATURE_LAST },
    { "bench_re_0062", R("[0-9]{3}"), 0, BENCH_LEN_LAST, BENCH_FEATURE_LAST },
    { "bench_re_0063", R("abl?"), 0, BENCH_LEN_LAST, BENCH_FEATURE_LAST },
    { "bench_re_0064", R("x[abc]4"), 0, BENCH_LEN_LAST, BENCH_FEATURE_LAST },
    { "bench_re_0065", R("a5"), 0, BENCH_LEN_LAST, BENCH_FEATURE_LAST },
    { "bench_re_0066", R("[a-z]+"), 0, BENCH_LEN_LAST, BENCH_FEATURE_LAST },
    { "bench_re_0067", R("[0-9]{2}"), 0, BENCH_LEN_LAST, BENCH_FEATURE_LAST },
    { "bench_re_0068", R("abq?"), 0, BENCH_LEN_LAST, BENCH_FEATURE_LAST },
    { "bench_re_0069", R("x[abc]9"), 0, BENCH_LEN_LAST, BENCH_FEATURE_LAST },
    { "bench_re_0070", R("a0"), 0, BENCH_LEN_LAST, BENCH_FEATURE_LAST },
    { "bench_re_0071", R("[a-z]"), 0, BENCH_LEN_LAST, BENCH_FEATURE_LAST },
    { "bench_re_0072", R("[0-9]{1}"), 0, BENCH_LEN_LAST, BENCH_FEATURE_LAST },
    { "bench_re_0073", R("abv?"), 0, BENCH_LEN_LAST, BENCH_FEATURE_LAST },
    { "bench_re_0074", R("x[abc]4"), 0, BENCH_LEN_LAST, BENCH_FEATURE_LAST },
    { "bench_re_0075", R("a5"), 0, BENCH_LEN_LAST, BENCH_FEATURE_LAST },
    { "bench_re_0076", R("[a-z]"), 0, BENCH_LEN_LAST, BENCH_FEATURE_LAST },
    { "bench_re_0077", R("[0-9]{3}"), 0, BENCH_LEN_LAST, BENCH_FEATURE_LAST },
    { "bench_re_0078", R("aba?"), 0, BENCH_LEN_LAST, BENCH_FEATURE_LAST },
    { "bench_re_0079", R("x[abc]9"), 0, BENCH_LEN_LAST, BENCH_FEATURE_LAST },
    { "bench_re_0080", R("a0"), 0, BENCH_LEN_LAST, BENCH_FEATURE_LAST },
    { "bench_re_0081", R("[a-z]+"), 0, BENCH_LEN_LAST, BENCH_FEATURE_LAST },
    { "bench_re_0082", R("[0-9]{2}"), 0, BENCH_LEN_LAST, BENCH_FEATURE_LAST },
    { "bench_re_0083", R("abf?"), 0, BENCH_LEN_LAST, BENCH_FEATURE_LAST },
    { "bench_re_0084", R("x[abc]4"), 0, BENCH_LEN_LAST, BENCH_FEATURE_LAST },
    { "bench_re_0085", R("a5"), 0, BENCH_LEN_LAST, BENCH_FEATURE_LAST },
    { "bench_re_0086", R("[a-z]"), 0, BENCH_LEN_LAST, BENCH_FEATURE_LAST },
    { "bench_re_0087", R("[0-9]{1}"), 0, BENCH_LEN_LAST, BENCH_FEATURE_LAST },
    { "bench_re_0088", R("abk?"), 0, BENCH_LEN_LAST, BENCH_FEATURE_LAST },
    { "bench_re_0089", R("x[abc]9"), 0, BENCH_LEN_LAST, BENCH_FEATURE_LAST },
    { "bench_re_0090", R("a0"), 0, BENCH_LEN_LAST, BENCH_FEATURE_LAST },
    { "bench_re_0091", R("[a-z]"), 0, BENCH_LEN_LAST, BENCH_FEATURE_LAST },
    { "bench_re_0092", R("[0-9]{3}"), 0, BENCH_LEN_LAST, BENCH_FEATURE_LAST },
    { "bench_re_0093", R("abp?"), 0, BENCH_LEN_LAST, BENCH_FEATURE_LAST },
    { "bench_re_0094", R("x[abc]4"), 0, BENCH_LEN_LAST, BENCH_FEATURE_LAST },
    { "bench_re_0095", R("a5"), 0, BENCH_LEN_LAST, BENCH_FEATURE_LAST },
    { "bench_re_0096", R("[a-z]+"), 0, BENCH_LEN_LAST, BENCH_FEATURE_LAST },
    { "bench_re_0097", R("[0-9]{2}"), 0, BENCH_LEN_LAST, BENCH_FEATURE_LAST },
    { "bench_re_0098", R("abu?"), 0, BENCH_LEN_LAST, BENCH_FEATURE_LAST },
    { "bench_re_0099", R("x[abc]9"), 0, BENCH_LEN_LAST, BENCH_FEATURE_LAST },
    { "bench_re_0100", R("(foo|baz)"), 0, BENCH_LEN_LAST, BENCH_FEATURE_LAST },
    { "bench_re_0101", R("(bar|qux|zap)[0-9]?"), 0, BENCH_LEN_LAST, BENCH_FEATURE_LAST },
    { "bench_re_0102", R("[A-Za-z]+(baz|zip)"), 0, BENCH_LEN_LAST, BENCH_FEATURE_LAST },
    { "bench_re_0103", R("(qux)+"), 0, BENCH_LEN_LAST, BENCH_FEATURE_LAST },
    { "bench_re_0104", R("(zip|[0-9]{2})"), 0, BENCH_LEN_LAST, BENCH_FEATURE_LAST },
    { "bench_re_0105", R("(zap|bar)"), 0, BENCH_LEN_LAST, BENCH_FEATURE_LAST },
    { "bench_re_0106", R("(foo|baz|zip)[0-9]?"), 0, BENCH_LEN_LAST, BENCH_FEATURE_LAST },
    { "bench_re_0107", R("[A-Za-z]+(bar|qux)"), 0, BENCH_LEN_LAST, BENCH_FEATURE_LAST },
    { "bench_re_0108", R("(baz)+"), 0, BENCH_LEN_LAST, BENCH_FEATURE_LAST },
    { "bench_re_0109", R("(qux|[0-9]{1})"), 0, BENCH_LEN_LAST, BENCH_FEATURE_LAST },
    { "bench_re_0110", R("(zip|foo)"), 0, BENCH_LEN_LAST, BENCH_FEATURE_LAST },
    { "bench_re_0111", R("(zap|bar|qux)[0-9]?"), 0, BENCH_LEN_LAST, BENCH_FEATURE_LAST },
    { "bench_re_0112", R("[A-Za-z]+(foo|baz)"), 0, BENCH_LEN_LAST, BENCH_FEATURE_LAST },
    { "bench_re_0113", R("(bar)+"), 0, BENCH_LEN_LAST, BENCH_FEATURE_LAST },
    { "bench_re_0114", R("(baz|[0-9]{3})"), 0, BENCH_LEN_LAST, BENCH_FEATURE_LAST },
    { "bench_re_0115", R("(qux|zap)"), 0, BENCH_LEN_LAST, BENCH_FEATURE_LAST },
    { "bench_re_0116", R("(zip|foo|baz)[0-9]?"), 0, BENCH_LEN_LAST, BENCH_FEATURE_LAST },
    { "bench_re_0117", R("[A-Za-z]+(zap|bar)"), 0, BENCH_LEN_LAST, BENCH_FEATURE_LAST },
    { "bench_re_0118", R("(foo)+"), 0, BENCH_LEN_LAST, BENCH_FEATURE_LAST },
    { "bench_re_0119", R("(bar|[0-9]{2})"), 0, BENCH_LEN_LAST, BENCH_FEATURE_LAST },
    { "bench_re_0120", R("(baz|zip)"), 0, BENCH_LEN_LAST, BENCH_FEATURE_LAST },
    { "bench_re_0121", R("(qux|zap|bar)[0-9]?"), 0, BENCH_LEN_LAST, BENCH_FEATURE_LAST },
    { "bench_re_0122", R("[A-Za-z]+(zip|foo)"), 0, BENCH_LEN_LAST, BENCH_FEATURE_LAST },
    { "bench_re_0123", R("(zap)+"), 0, BENCH_LEN_LAST, BENCH_FEATURE_LAST },
    { "bench_re_0124", R("(foo|[0-9]{1})"), 0, BENCH_LEN_LAST, BENCH_FEATURE_LAST },
    { "bench_re_0125", R("(bar|qux)"), 0, BENCH_LEN_LAST, BENCH_FEATURE_LAST },
    { "bench_re_0126", R("(baz|zip|foo)[0-9]?"), 0, BENCH_LEN_LAST, BENCH_FEATURE_LAST },
    { "bench_re_0127", R("[A-Za-z]+(qux|zap)"), 0, BENCH_LEN_LAST, BENCH_FEATURE_LAST },
    { "bench_re_0128", R("(zip)+"), 0, BENCH_LEN_LAST, BENCH_FEATURE_LAST },
    { "bench_re_0129", R("(zap|[0-9]{3})"), 0, BENCH_LEN_LAST, BENCH_FEATURE_LAST },
    { "bench_re_0130", R("(foo|baz)"), 0, BENCH_LEN_LAST, BENCH_FEATURE_LAST },
    { "bench_re_0131", R("(bar|qux|zap)[0-9]?"), 0, BENCH_LEN_LAST, BENCH_FEATURE_LAST },
    { "bench_re_0132", R("[A-Za-z]+(baz|zip)"), 0, BENCH_LEN_LAST, BENCH_FEATURE_LAST },
    { "bench_re_0133", R("(qux)+"), 0, BENCH_LEN_LAST, BENCH_FEATURE_LAST },
    { "bench_re_0134", R("(zip|[0-9]{2})"), 0, BENCH_LEN_LAST, BENCH_FEATURE_LAST },
    { "bench_re_0135", R("(zap|bar)"), 0, BENCH_LEN_LAST, BENCH_FEATURE_LAST },
    { "bench_re_0136", R("(foo|baz|zip)[0-9]?"), 0, BENCH_LEN_LAST, BENCH_FEATURE_LAST },
    { "bench_re_0137", R("[A-Za-z]+(bar|qux)"), 0, BENCH_LEN_LAST, BENCH_FEATURE_LAST },
    { "bench_re_0138", R("(baz)+"), 0, BENCH_LEN_LAST, BENCH_FEATURE_LAST },
    { "bench_re_0139", R("(qux|[0-9]{1})"), 0, BENCH_LEN_LAST, BENCH_FEATURE_LAST },
    { "bench_re_0140", R("(zip|foo)"), 0, BENCH_LEN_LAST, BENCH_FEATURE_LAST },
    { "bench_re_0141", R("(zap|bar|qux)[0-9]?"), 0, BENCH_LEN_LAST, BENCH_FEATURE_LAST },
    { "bench_re_0142", R("[A-Za-z]+(foo|baz)"), 0, BENCH_LEN_LAST, BENCH_FEATURE_LAST },
    { "bench_re_0143", R("(bar)+"), 0, BENCH_LEN_LAST, BENCH_FEATURE_LAST },
    { "bench_re_0144", R("(baz|[0-9]{3})"), 0, BENCH_LEN_LAST, BENCH_FEATURE_LAST },
    { "bench_re_0145", R("(qux|zap)"), 0, BENCH_LEN_LAST, BENCH_FEATURE_LAST },
    { "bench_re_0146", R("(zip|foo|baz)[0-9]?"), 0, BENCH_LEN_LAST, BENCH_FEATURE_LAST },
    { "bench_re_0147", R("[A-Za-z]+(zap|bar)"), 0, BENCH_LEN_LAST, BENCH_FEATURE_LAST },
    { "bench_re_0148", R("(foo)+"), 0, BENCH_LEN_LAST, BENCH_FEATURE_LAST },
    { "bench_re_0149", R("(bar|[0-9]{2})"), 0, BENCH_LEN_LAST, BENCH_FEATURE_LAST },
    { "bench_re_0150", R("(baz|zip)"), 0, BENCH_LEN_LAST, BENCH_FEATURE_LAST },
    { "bench_re_0151", R("(qux|zap|bar)[0-9]?"), 0, BENCH_LEN_LAST, BENCH_FEATURE_LAST },
    { "bench_re_0152", R("[A-Za-z]+(zip|foo)"), 0, BENCH_LEN_LAST, BENCH_FEATURE_LAST },
    { "bench_re_0153", R("(zap)+"), 0, BENCH_LEN_LAST, BENCH_FEATURE_LAST },
    { "bench_re_0154", R("(foo|[0-9]{1})"), 0, BENCH_LEN_LAST, BENCH_FEATURE_LAST },
    { "bench_re_0155", R("(bar|qux)"), 0, BENCH_LEN_LAST, BENCH_FEATURE_LAST },
    { "bench_re_0156", R("(baz|zip|foo)[0-9]?"), 0, BENCH_LEN_LAST, BENCH_FEATURE_LAST },
    { "bench_re_0157", R("[A-Za-z]+(qux|zap)"), 0, BENCH_LEN_LAST, BENCH_FEATURE_LAST },
    { "bench_re_0158", R("(zip)+"), 0, BENCH_LEN_LAST, BENCH_FEATURE_LAST },
    { "bench_re_0159", R("(zap|[0-9]{3})"), 0, BENCH_LEN_LAST, BENCH_FEATURE_LAST },
    { "bench_re_0160", R("(foo|baz)"), 0, BENCH_LEN_LAST, BENCH_FEATURE_LAST },
    { "bench_re_0161", R("(bar|qux|zap)[0-9]?"), 0, BENCH_LEN_LAST, BENCH_FEATURE_LAST },
    { "bench_re_0162", R("[A-Za-z]+(baz|zip)"), 0, BENCH_LEN_LAST, BENCH_FEATURE_LAST },
    { "bench_re_0163", R("(qux)+"), 0, BENCH_LEN_LAST, BENCH_FEATURE_LAST },
    { "bench_re_0164", R("(zip|[0-9]{2})"), 0, BENCH_LEN_LAST, BENCH_FEATURE_LAST },
    { "bench_re_0165", R("(zap|bar)"), 0, BENCH_LEN_LAST, BENCH_FEATURE_LAST },
    { "bench_re_0166", R("(foo|baz|zip)[0-9]?"), 0, BENCH_LEN_LAST, BENCH_FEATURE_LAST },
    { "bench_re_0167", R("[A-Za-z]+(bar|qux)"), 0, BENCH_LEN_LAST, BENCH_FEATURE_LAST },
    { "bench_re_0168", R("(baz)+"), 0, BENCH_LEN_LAST, BENCH_FEATURE_LAST },
    { "bench_re_0169", R("(qux|[0-9]{1})"), 0, BENCH_LEN_LAST, BENCH_FEATURE_LAST },
    { "bench_re_0170", R("(zip|foo)"), 0, BENCH_LEN_LAST, BENCH_FEATURE_LAST },
    { "bench_re_0171", R("(zap|bar|qux)[0-9]?"), 0, BENCH_LEN_LAST, BENCH_FEATURE_LAST },
    { "bench_re_0172", R("[A-Za-z]+(foo|baz)"), 0, BENCH_LEN_LAST, BENCH_FEATURE_LAST },
    { "bench_re_0173", R("(bar)+"), 0, BENCH_LEN_LAST, BENCH_FEATURE_LAST },
    { "bench_re_0174", R("(baz|[0-9]{3})"), 0, BENCH_LEN_LAST, BENCH_FEATURE_LAST },
    { "bench_re_0175", R("(qux|zap)"), 0, BENCH_LEN_LAST, BENCH_FEATURE_LAST },
    { "bench_re_0176", R("(zip|foo|baz)[0-9]?"), 0, BENCH_LEN_LAST, BENCH_FEATURE_LAST },
    { "bench_re_0177", R("[A-Za-z]+(zap|bar)"), 0, BENCH_LEN_LAST, BENCH_FEATURE_LAST },
    { "bench_re_0178", R("(foo)+"), 0, BENCH_LEN_LAST, BENCH_FEATURE_LAST },
    { "bench_re_0179", R("(bar|[0-9]{2})"), 0, BENCH_LEN_LAST, BENCH_FEATURE_LAST },
    { "bench_re_0180", R("(baz|zip)"), 0, BENCH_LEN_LAST, BENCH_FEATURE_LAST },
    { "bench_re_0181", R("(qux|zap|bar)[0-9]?"), 0, BENCH_LEN_LAST, BENCH_FEATURE_LAST },
    { "bench_re_0182", R("[A-Za-z]+(zip|foo)"), 0, BENCH_LEN_LAST, BENCH_FEATURE_LAST },
    { "bench_re_0183", R("(zap)+"), 0, BENCH_LEN_LAST, BENCH_FEATURE_LAST },
    { "bench_re_0184", R("(foo|[0-9]{1})"), 0, BENCH_LEN_LAST, BENCH_FEATURE_LAST },
    { "bench_re_0185", R("(bar|qux)"), 0, BENCH_LEN_LAST, BENCH_FEATURE_LAST },
    { "bench_re_0186", R("(baz|zip|foo)[0-9]?"), 0, BENCH_LEN_LAST, BENCH_FEATURE_LAST },
    { "bench_re_0187", R("[A-Za-z]+(qux|zap)"), 0, BENCH_LEN_LAST, BENCH_FEATURE_LAST },
    { "bench_re_0188", R("(zip)+"), 0, BENCH_LEN_LAST, BENCH_FEATURE_LAST },
    { "bench_re_0189", R("(zap|[0-9]{3})"), 0, BENCH_LEN_LAST, BENCH_FEATURE_LAST },
    { "bench_re_0190", R("(foo|baz)"), 0, BENCH_LEN_LAST, BENCH_FEATURE_LAST },
    { "bench_re_0191", R("(bar|qux|zap)[0-9]?"), 0, BENCH_LEN_LAST, BENCH_FEATURE_LAST },
    { "bench_re_0192", R("[A-Za-z]+(baz|zip)"), 0, BENCH_LEN_LAST, BENCH_FEATURE_LAST },
    { "bench_re_0193", R("(qux)+"), 0, BENCH_LEN_LAST, BENCH_FEATURE_LAST },
    { "bench_re_0194", R("(zip|[0-9]{2})"), 0, BENCH_LEN_LAST, BENCH_FEATURE_LAST },
    { "bench_re_0195", R("(zap|bar)"), 0, BENCH_LEN_LAST, BENCH_FEATURE_LAST },
    { "bench_re_0196", R("(foo|baz|zip)[0-9]?"), 0, BENCH_LEN_LAST, BENCH_FEATURE_LAST },
    { "bench_re_0197", R("[A-Za-z]+(bar|qux)"), 0, BENCH_LEN_LAST, BENCH_FEATURE_LAST },
    { "bench_re_0198", R("(baz)+"), 0, BENCH_LEN_LAST, BENCH_FEATURE_LAST },
    { "bench_re_0199", R("(qux|[0-9]{1})"), 0, BENCH_LEN_LAST, BENCH_FEATURE_LAST },
    { "bench_re_0200", R("^foo[0-9]*$"), 0, BENCH_LEN_LAST, BENCH_FEATURE_LAST },
    { "bench_re_0201", R("\\bbar\\b"), 0, BENCH_LEN_LAST, BENCH_FEATURE_LAST },
    { "bench_re_0202", R("\\<baz[0-9]?\\>"), 0, BENCH_LEN_LAST, BENCH_FEATURE_LAST },
    { "bench_re_0203", R("^[[:space:]]*alpha[[:space:]]*$"), 0, BENCH_LEN_LAST, BENCH_FEATURE_LAST },
    { "bench_re_0204", R("\\B[a-z]{2}[0-9]?\\B"), 0, BENCH_LEN_LAST, BENCH_FEATURE_LAST },
    { "bench_re_0205", R("^foo[0-9]*$"), 0, BENCH_LEN_LAST, BENCH_FEATURE_LAST },
    { "bench_re_0206", R("\\bbar\\b"), 0, BENCH_LEN_LAST, BENCH_FEATURE_LAST },
    { "bench_re_0207", R("\\<baz[0-9]?\\>"), 0, BENCH_LEN_LAST, BENCH_FEATURE_LAST },
    { "bench_re_0208", R("^[[:space:]]*alpha[[:space:]]*$"), 0, BENCH_LEN_LAST, BENCH_FEATURE_LAST },
    { "bench_re_0209", R("\\B[a-z]{3}[0-9]?\\B"), 0, BENCH_LEN_LAST, BENCH_FEATURE_LAST },
    { "bench_re_0210", R("^foo[0-9]*$"), 0, BENCH_LEN_LAST, BENCH_FEATURE_LAST },
    { "bench_re_0211", R("\\bbar\\b"), 0, BENCH_LEN_LAST, BENCH_FEATURE_LAST },
    { "bench_re_0212", R("\\<baz[0-9]?\\>"), 0, BENCH_LEN_LAST, BENCH_FEATURE_LAST },
    { "bench_re_0213", R("^[[:space:]]*alpha[[:space:]]*$"), 0, BENCH_LEN_LAST, BENCH_FEATURE_LAST },
    { "bench_re_0214", R("\\B[a-z]{4}[0-9]?\\B"), 0, BENCH_LEN_LAST, BENCH_FEATURE_LAST },
    { "bench_re_0215", R("^foo[0-9]*$"), 0, BENCH_LEN_LAST, BENCH_FEATURE_LAST },
    { "bench_re_0216", R("\\bbar\\b"), 0, BENCH_LEN_LAST, BENCH_FEATURE_LAST },
    { "bench_re_0217", R("\\<baz[0-9]?\\>"), 0, BENCH_LEN_LAST, BENCH_FEATURE_LAST },
    { "bench_re_0218", R("^[[:space:]]*alpha[[:space:]]*$"), 0, BENCH_LEN_LAST, BENCH_FEATURE_LAST },
    { "bench_re_0219", R("\\B[a-z]{5}[0-9]?\\B"), 0, BENCH_LEN_LAST, BENCH_FEATURE_LAST },
    { "bench_re_0220", R("^foo[0-9]*$"), 0, BENCH_LEN_LAST, BENCH_FEATURE_LAST },
    { "bench_re_0221", R("\\bbar\\b"), 0, BENCH_LEN_LAST, BENCH_FEATURE_LAST },
    { "bench_re_0222", R("\\<baz[0-9]?\\>"), 0, BENCH_LEN_LAST, BENCH_FEATURE_LAST },
    { "bench_re_0223", R("^[[:space:]]*alpha[[:space:]]*$"), 0, BENCH_LEN_LAST, BENCH_FEATURE_LAST },
    { "bench_re_0224", R("\\B[a-z]{2}[0-9]?\\B"), 0, BENCH_LEN_LAST, BENCH_FEATURE_LAST },
    { "bench_re_0225", R("^foo[0-9]*$"), 0, BENCH_LEN_LAST, BENCH_FEATURE_LAST },
    { "bench_re_0226", R("\\bbar\\b"), 0, BENCH_LEN_LAST, BENCH_FEATURE_LAST },
    { "bench_re_0227", R("\\<baz[0-9]?\\>"), 0, BENCH_LEN_LAST, BENCH_FEATURE_LAST },
    { "bench_re_0228", R("^[[:space:]]*alpha[[:space:]]*$"), 0, BENCH_LEN_LAST, BENCH_FEATURE_LAST },
    { "bench_re_0229", R("\\B[a-z]{3}[0-9]?\\B"), 0, BENCH_LEN_LAST, BENCH_FEATURE_LAST },
    { "bench_re_0230", R("^foo[0-9]*$"), 0, BENCH_LEN_LAST, BENCH_FEATURE_LAST },
    { "bench_re_0231", R("\\bbar\\b"), 0, BENCH_LEN_LAST, BENCH_FEATURE_LAST },
    { "bench_re_0232", R("\\<baz[0-9]?\\>"), 0, BENCH_LEN_LAST, BENCH_FEATURE_LAST },
    { "bench_re_0233", R("^[[:space:]]*alpha[[:space:]]*$"), 0, BENCH_LEN_LAST, BENCH_FEATURE_LAST },
    { "bench_re_0234", R("\\B[a-z]{4}[0-9]?\\B"), 0, BENCH_LEN_LAST, BENCH_FEATURE_LAST },
    { "bench_re_0235", R("^foo[0-9]*$"), 0, BENCH_LEN_LAST, BENCH_FEATURE_LAST },
    { "bench_re_0236", R("\\bbar\\b"), 0, BENCH_LEN_LAST, BENCH_FEATURE_LAST },
    { "bench_re_0237", R("\\<baz[0-9]?\\>"), 0, BENCH_LEN_LAST, BENCH_FEATURE_LAST },
    { "bench_re_0238", R("^[[:space:]]*alpha[[:space:]]*$"), 0, BENCH_LEN_LAST, BENCH_FEATURE_LAST },
    { "bench_re_0239", R("\\B[a-z]{5}[0-9]?\\B"), 0, BENCH_LEN_LAST, BENCH_FEATURE_LAST },
    { "bench_re_0240", R("^foo[0-9]*$"), 0, BENCH_LEN_LAST, BENCH_FEATURE_LAST },
    { "bench_re_0241", R("\\bbar\\b"), 0, BENCH_LEN_LAST, BENCH_FEATURE_LAST },
    { "bench_re_0242", R("\\<baz[0-9]?\\>"), 0, BENCH_LEN_LAST, BENCH_FEATURE_LAST },
    { "bench_re_0243", R("^[[:space:]]*alpha[[:space:]]*$"), 0, BENCH_LEN_LAST, BENCH_FEATURE_LAST },
    { "bench_re_0244", R("\\B[a-z]{2}[0-9]?\\B"), 0, BENCH_LEN_LAST, BENCH_FEATURE_LAST },
    { "bench_re_0245", R("^foo[0-9]*$"), 0, BENCH_LEN_LAST, BENCH_FEATURE_LAST },
    { "bench_re_0246", R("\\bbar\\b"), 0, BENCH_LEN_LAST, BENCH_FEATURE_LAST },
    { "bench_re_0247", R("\\<baz[0-9]?\\>"), 0, BENCH_LEN_LAST, BENCH_FEATURE_LAST },
    { "bench_re_0248", R("^[[:space:]]*alpha[[:space:]]*$"), 0, BENCH_LEN_LAST, BENCH_FEATURE_LAST },
    { "bench_re_0249", R("\\B[a-z]{3}[0-9]?\\B"), 0, BENCH_LEN_LAST, BENCH_FEATURE_LAST },
    { "bench_re_0250", R("^foo[0-9]*$"), 0, BENCH_LEN_LAST, BENCH_FEATURE_LAST },
    { "bench_re_0251", R("\\bbar\\b"), 0, BENCH_LEN_LAST, BENCH_FEATURE_LAST },
    { "bench_re_0252", R("\\<baz[0-9]?\\>"), 0, BENCH_LEN_LAST, BENCH_FEATURE_LAST },
    { "bench_re_0253", R("^[[:space:]]*alpha[[:space:]]*$"), 0, BENCH_LEN_LAST, BENCH_FEATURE_LAST },
    { "bench_re_0254", R("\\B[a-z]{4}[0-9]?\\B"), 0, BENCH_LEN_LAST, BENCH_FEATURE_LAST },
    { "bench_re_0255", R("^foo[0-9]*$"), 0, BENCH_LEN_LAST, BENCH_FEATURE_LAST },
    { "bench_re_0256", R("\\bbar\\b"), 0, BENCH_LEN_LAST, BENCH_FEATURE_LAST },
    { "bench_re_0257", R("\\<baz[0-9]?\\>"), 0, BENCH_LEN_LAST, BENCH_FEATURE_LAST },
    { "bench_re_0258", R("^[[:space:]]*alpha[[:space:]]*$"), 0, BENCH_LEN_LAST, BENCH_FEATURE_LAST },
    { "bench_re_0259", R("\\B[a-z]{5}[0-9]?\\B"), 0, BENCH_LEN_LAST, BENCH_FEATURE_LAST },
    { "bench_re_0260", R("^foo[0-9]*$"), 0, BENCH_LEN_LAST, BENCH_FEATURE_LAST },
    { "bench_re_0261", R("\\bbar\\b"), 0, BENCH_LEN_LAST, BENCH_FEATURE_LAST },
    { "bench_re_0262", R("\\<baz[0-9]?\\>"), 0, BENCH_LEN_LAST, BENCH_FEATURE_LAST },
    { "bench_re_0263", R("^[[:space:]]*alpha[[:space:]]*$"), 0, BENCH_LEN_LAST, BENCH_FEATURE_LAST },
    { "bench_re_0264", R("\\B[a-z]{2}[0-9]?\\B"), 0, BENCH_LEN_LAST, BENCH_FEATURE_LAST },
    { "bench_re_0265", R("^foo[0-9]*$"), 0, BENCH_LEN_LAST, BENCH_FEATURE_LAST },
    { "bench_re_0266", R("\\bbar\\b"), 0, BENCH_LEN_LAST, BENCH_FEATURE_LAST },
    { "bench_re_0267", R("\\<baz[0-9]?\\>"), 0, BENCH_LEN_LAST, BENCH_FEATURE_LAST },
    { "bench_re_0268", R("^[[:space:]]*alpha[[:space:]]*$"), 0, BENCH_LEN_LAST, BENCH_FEATURE_LAST },
    { "bench_re_0269", R("\\B[a-z]{3}[0-9]?\\B"), 0, BENCH_LEN_LAST, BENCH_FEATURE_LAST },
    { "bench_re_0270", R("^foo[0-9]*$"), 0, BENCH_LEN_LAST, BENCH_FEATURE_LAST },
    { "bench_re_0271", R("\\bbar\\b"), 0, BENCH_LEN_LAST, BENCH_FEATURE_LAST },
    { "bench_re_0272", R("\\<baz[0-9]?\\>"), 0, BENCH_LEN_LAST, BENCH_FEATURE_LAST },
    { "bench_re_0273", R("^[[:space:]]*alpha[[:space:]]*$"), 0, BENCH_LEN_LAST, BENCH_FEATURE_LAST },
    { "bench_re_0274", R("\\B[a-z]{4}[0-9]?\\B"), 0, BENCH_LEN_LAST, BENCH_FEATURE_LAST },
    { "bench_re_0275", R("^foo[0-9]*$"), 0, BENCH_LEN_LAST, BENCH_FEATURE_LAST },
    { "bench_re_0276", R("\\bbar\\b"), 0, BENCH_LEN_LAST, BENCH_FEATURE_LAST },
    { "bench_re_0277", R("\\<baz[0-9]?\\>"), 0, BENCH_LEN_LAST, BENCH_FEATURE_LAST },
    { "bench_re_0278", R("^[[:space:]]*alpha[[:space:]]*$"), 0, BENCH_LEN_LAST, BENCH_FEATURE_LAST },
    { "bench_re_0279", R("\\B[a-z]{5}[0-9]?\\B"), 0, BENCH_LEN_LAST, BENCH_FEATURE_LAST },
    { "bench_re_0280", R("^foo[0-9]*$"), 0, BENCH_LEN_LAST, BENCH_FEATURE_LAST },
    { "bench_re_0281", R("\\bbar\\b"), 0, BENCH_LEN_LAST, BENCH_FEATURE_LAST },
    { "bench_re_0282", R("\\<baz[0-9]?\\>"), 0, BENCH_LEN_LAST, BENCH_FEATURE_LAST },
    { "bench_re_0283", R("^[[:space:]]*alpha[[:space:]]*$"), 0, BENCH_LEN_LAST, BENCH_FEATURE_LAST },
    { "bench_re_0284", R("\\B[a-z]{2}[0-9]?\\B"), 0, BENCH_LEN_LAST, BENCH_FEATURE_LAST },
    { "bench_re_0285", R("^foo[0-9]*$"), 0, BENCH_LEN_LAST, BENCH_FEATURE_LAST },
    { "bench_re_0286", R("\\bbar\\b"), 0, BENCH_LEN_LAST, BENCH_FEATURE_LAST },
    { "bench_re_0287", R("\\<baz[0-9]?\\>"), 0, BENCH_LEN_LAST, BENCH_FEATURE_LAST },
    { "bench_re_0288", R("^[[:space:]]*alpha[[:space:]]*$"), 0, BENCH_LEN_LAST, BENCH_FEATURE_LAST },
    { "bench_re_0289", R("\\B[a-z]{3}[0-9]?\\B"), 0, BENCH_LEN_LAST, BENCH_FEATURE_LAST },
    { "bench_re_0290", R("^foo[0-9]*$"), 0, BENCH_LEN_LAST, BENCH_FEATURE_LAST },
    { "bench_re_0291", R("\\bbar\\b"), 0, BENCH_LEN_LAST, BENCH_FEATURE_LAST },
    { "bench_re_0292", R("\\<baz[0-9]?\\>"), 0, BENCH_LEN_LAST, BENCH_FEATURE_LAST },
    { "bench_re_0293", R("^[[:space:]]*alpha[[:space:]]*$"), 0, BENCH_LEN_LAST, BENCH_FEATURE_LAST },
    { "bench_re_0294", R("\\B[a-z]{4}[0-9]?\\B"), 0, BENCH_LEN_LAST, BENCH_FEATURE_LAST },
    { "bench_re_0295", R("^foo[0-9]*$"), 0, BENCH_LEN_LAST, BENCH_FEATURE_LAST },
    { "bench_re_0296", R("\\bbar\\b"), 0, BENCH_LEN_LAST, BENCH_FEATURE_LAST },
    { "bench_re_0297", R("\\<baz[0-9]?\\>"), 0, BENCH_LEN_LAST, BENCH_FEATURE_LAST },
    { "bench_re_0298", R("^[[:space:]]*alpha[[:space:]]*$"), 0, BENCH_LEN_LAST, BENCH_FEATURE_LAST },
    { "bench_re_0299", R("\\B[a-z]{5}[0-9]?\\B"), 0, BENCH_LEN_LAST, BENCH_FEATURE_LAST },
    { "bench_re_0300", R("[a-z]{1,3}[0-9]{1}"), 0, BENCH_LEN_LAST, BENCH_FEATURE_LAST },
    { "bench_re_0301", R("([abc]{2,5}|[0-9]{2,5})"), 0, BENCH_LEN_LAST, BENCH_FEATURE_LAST },
    { "bench_re_0302", R("([a-z]+[-_])?[0-9]{3,7}"), 0, BENCH_LEN_LAST, BENCH_FEATURE_LAST },
    { "bench_re_0303", R("([A-Z][a-z]{4,6})[.]?"), 0, BENCH_LEN_LAST, BENCH_FEATURE_LAST },
    { "bench_re_0304", R("([a-z]{1}[0-9]?)+"), 0, BENCH_LEN_LAST, BENCH_FEATURE_LAST },
    { "bench_re_0305", R("[a-z]{2,6}[0-9]{2}"), 0, BENCH_LEN_LAST, BENCH_FEATURE_LAST },
    { "bench_re_0306", R("([abc]{3,5}|[0-9]{3,5})"), 0, BENCH_LEN_LAST, BENCH_FEATURE_LAST },
    { "bench_re_0307", R("([a-z]+[-_])?[0-9]{4,7}"), 0, BENCH_LEN_LAST, BENCH_FEATURE_LAST },
    { "bench_re_0308", R("([A-Z][a-z]{1,5})[.]?"), 0, BENCH_LEN_LAST, BENCH_FEATURE_LAST },
    { "bench_re_0309", R("([a-z]{2}[0-9]?)+"), 0, BENCH_LEN_LAST, BENCH_FEATURE_LAST },
    { "bench_re_0310", R("[a-z]{3,6}[0-9]{3}"), 0, BENCH_LEN_LAST, BENCH_FEATURE_LAST },
    { "bench_re_0311", R("([abc]{4,8}|[0-9]{4,8})"), 0, BENCH_LEN_LAST, BENCH_FEATURE_LAST },
    { "bench_re_0312", R("([a-z]+[-_])?[0-9]{1,3}"), 0, BENCH_LEN_LAST, BENCH_FEATURE_LAST },
    { "bench_re_0313", R("([A-Z][a-z]{2,5})[.]?"), 0, BENCH_LEN_LAST, BENCH_FEATURE_LAST },
    { "bench_re_0314", R("([a-z]{3}[0-9]?)+"), 0, BENCH_LEN_LAST, BENCH_FEATURE_LAST },
    { "bench_re_0315", R("[a-z]{4,6}[0-9]{4}"), 0, BENCH_LEN_LAST, BENCH_FEATURE_LAST },
    { "bench_re_0316", R("([abc]{1,4}|[0-9]{1,4})"), 0, BENCH_LEN_LAST, BENCH_FEATURE_LAST },
    { "bench_re_0317", R("([a-z]+[-_])?[0-9]{2,6}"), 0, BENCH_LEN_LAST, BENCH_FEATURE_LAST },
    { "bench_re_0318", R("([A-Z][a-z]{3,5})[.]?"), 0, BENCH_LEN_LAST, BENCH_FEATURE_LAST },
    { "bench_re_0319", R("([a-z]{4}[0-9]?)+"), 0, BENCH_LEN_LAST, BENCH_FEATURE_LAST },
    { "bench_re_0320", R("[a-z]{1,5}[0-9]{1}"), 0, BENCH_LEN_LAST, BENCH_FEATURE_LAST },
    { "bench_re_0321", R("([abc]{2,4}|[0-9]{2,4})"), 0, BENCH_LEN_LAST, BENCH_FEATURE_LAST },
    { "bench_re_0322", R("([a-z]+[-_])?[0-9]{3,6}"), 0, BENCH_LEN_LAST, BENCH_FEATURE_LAST },
    { "bench_re_0323", R("([A-Z][a-z]{4,8})[.]?"), 0, BENCH_LEN_LAST, BENCH_FEATURE_LAST },
    { "bench_re_0324", R("([a-z]{1}[0-9]?)+"), 0, BENCH_LEN_LAST, BENCH_FEATURE_LAST },
    { "bench_re_0325", R("[a-z]{2,5}[0-9]{2}"), 0, BENCH_LEN_LAST, BENCH_FEATURE_LAST },
    { "bench_re_0326", R("([abc]{3,7}|[0-9]{3,7})"), 0, BENCH_LEN_LAST, BENCH_FEATURE_LAST },
    { "bench_re_0327", R("([a-z]+[-_])?[0-9]{4,6}"), 0, BENCH_LEN_LAST, BENCH_FEATURE_LAST },
    { "bench_re_0328", R("([A-Z][a-z]{1,4})[.]?"), 0, BENCH_LEN_LAST, BENCH_FEATURE_LAST },
    { "bench_re_0329", R("([a-z]{2}[0-9]?)+"), 0, BENCH_LEN_LAST, BENCH_FEATURE_LAST },
    { "bench_re_0330", R("[a-z]{3,5}[0-9]{3}"), 0, BENCH_LEN_LAST, BENCH_FEATURE_LAST },
    { "bench_re_0331", R("([abc]{4,7}|[0-9]{4,7})"), 0, BENCH_LEN_LAST, BENCH_FEATURE_LAST },
    { "bench_re_0332", R("([a-z]+[-_])?[0-9]{1,5}"), 0, BENCH_LEN_LAST, BENCH_FEATURE_LAST },
    { "bench_re_0333", R("([A-Z][a-z]{2,4})[.]?"), 0, BENCH_LEN_LAST, BENCH_FEATURE_LAST },
    { "bench_re_0334", R("([a-z]{3}[0-9]?)+"), 0, BENCH_LEN_LAST, BENCH_FEATURE_LAST },
    { "bench_re_0335", R("[a-z]{4,8}[0-9]{4}"), 0, BENCH_LEN_LAST, BENCH_FEATURE_LAST },
    { "bench_re_0336", R("([abc]{1,3}|[0-9]{1,3})"), 0, BENCH_LEN_LAST, BENCH_FEATURE_LAST },
    { "bench_re_0337", R("([a-z]+[-_])?[0-9]{2,5}"), 0, BENCH_LEN_LAST, BENCH_FEATURE_LAST },
    { "bench_re_0338", R("([A-Z][a-z]{3,7})[.]?"), 0, BENCH_LEN_LAST, BENCH_FEATURE_LAST },
    { "bench_re_0339", R("([a-z]{4}[0-9]?)+"), 0, BENCH_LEN_LAST, BENCH_FEATURE_LAST },
    { "bench_re_0340", R("[a-z]{1,4}[0-9]{1}"), 0, BENCH_LEN_LAST, BENCH_FEATURE_LAST },
    { "bench_re_0341", R("([abc]{2,6}|[0-9]{2,6})"), 0, BENCH_LEN_LAST, BENCH_FEATURE_LAST },
    { "bench_re_0342", R("([a-z]+[-_])?[0-9]{3,5}"), 0, BENCH_LEN_LAST, BENCH_FEATURE_LAST },
    { "bench_re_0343", R("([A-Z][a-z]{4,7})[.]?"), 0, BENCH_LEN_LAST, BENCH_FEATURE_LAST },
    { "bench_re_0344", R("([a-z]{1}[0-9]?)+"), 0, BENCH_LEN_LAST, BENCH_FEATURE_LAST },
    { "bench_re_0345", R("[a-z]{2,4}[0-9]{2}"), 0, BENCH_LEN_LAST, BENCH_FEATURE_LAST },
    { "bench_re_0346", R("([abc]{3,6}|[0-9]{3,6})"), 0, BENCH_LEN_LAST, BENCH_FEATURE_LAST },
    { "bench_re_0347", R("([a-z]+[-_])?[0-9]{4,8}"), 0, BENCH_LEN_LAST, BENCH_FEATURE_LAST },
    { "bench_re_0348", R("([A-Z][a-z]{1,3})[.]?"), 0, BENCH_LEN_LAST, BENCH_FEATURE_LAST },
    { "bench_re_0349", R("([a-z]{2}[0-9]?)+"), 0, BENCH_LEN_LAST, BENCH_FEATURE_LAST },
    { "bench_re_0350", R("[a-z]{3,7}[0-9]{3}"), 0, BENCH_LEN_LAST, BENCH_FEATURE_LAST },
    { "bench_re_0351", R("([abc]{4,6}|[0-9]{4,6})"), 0, BENCH_LEN_LAST, BENCH_FEATURE_LAST },
    { "bench_re_0352", R("([a-z]+[-_])?[0-9]{1,4}"), 0, BENCH_LEN_LAST, BENCH_FEATURE_LAST },
    { "bench_re_0353", R("([A-Z][a-z]{2,6})[.]?"), 0, BENCH_LEN_LAST, BENCH_FEATURE_LAST },
    { "bench_re_0354", R("([a-z]{3}[0-9]?)+"), 0, BENCH_LEN_LAST, BENCH_FEATURE_LAST },
    { "bench_re_0355", R("[a-z]{4,7}[0-9]{4}"), 0, BENCH_LEN_LAST, BENCH_FEATURE_LAST },
    { "bench_re_0356", R("([abc]{1,5}|[0-9]{1,5})"), 0, BENCH_LEN_LAST, BENCH_FEATURE_LAST },
    { "bench_re_0357", R("([a-z]+[-_])?[0-9]{2,4}"), 0, BENCH_LEN_LAST, BENCH_FEATURE_LAST },
    { "bench_re_0358", R("([A-Z][a-z]{3,6})[.]?"), 0, BENCH_LEN_LAST, BENCH_FEATURE_LAST },
    { "bench_re_0359", R("([a-z]{4}[0-9]?)+"), 0, BENCH_LEN_LAST, BENCH_FEATURE_LAST },
    { "bench_re_0360", R("[a-z]{1,3}[0-9]{1}"), 0, BENCH_LEN_LAST, BENCH_FEATURE_LAST },
    { "bench_re_0361", R("([abc]{2,5}|[0-9]{2,5})"), 0, BENCH_LEN_LAST, BENCH_FEATURE_LAST },
    { "bench_re_0362", R("([a-z]+[-_])?[0-9]{3,7}"), 0, BENCH_LEN_LAST, BENCH_FEATURE_LAST },
    { "bench_re_0363", R("([A-Z][a-z]{4,6})[.]?"), 0, BENCH_LEN_LAST, BENCH_FEATURE_LAST },
    { "bench_re_0364", R("([a-z]{1}[0-9]?)+"), 0, BENCH_LEN_LAST, BENCH_FEATURE_LAST },
    { "bench_re_0365", R("[a-z]{2,6}[0-9]{2}"), 0, BENCH_LEN_LAST, BENCH_FEATURE_LAST },
    { "bench_re_0366", R("([abc]{3,5}|[0-9]{3,5})"), 0, BENCH_LEN_LAST, BENCH_FEATURE_LAST },
    { "bench_re_0367", R("([a-z]+[-_])?[0-9]{4,7}"), 0, BENCH_LEN_LAST, BENCH_FEATURE_LAST },
    { "bench_re_0368", R("([A-Z][a-z]{1,5})[.]?"), 0, BENCH_LEN_LAST, BENCH_FEATURE_LAST },
    { "bench_re_0369", R("([a-z]{2}[0-9]?)+"), 0, BENCH_LEN_LAST, BENCH_FEATURE_LAST },
    { "bench_re_0370", R("[a-z]{3,6}[0-9]{3}"), 0, BENCH_LEN_LAST, BENCH_FEATURE_LAST },
    { "bench_re_0371", R("([abc]{4,8}|[0-9]{4,8})"), 0, BENCH_LEN_LAST, BENCH_FEATURE_LAST },
    { "bench_re_0372", R("([a-z]+[-_])?[0-9]{1,3}"), 0, BENCH_LEN_LAST, BENCH_FEATURE_LAST },
    { "bench_re_0373", R("([A-Z][a-z]{2,5})[.]?"), 0, BENCH_LEN_LAST, BENCH_FEATURE_LAST },
    { "bench_re_0374", R("([a-z]{3}[0-9]?)+"), 0, BENCH_LEN_LAST, BENCH_FEATURE_LAST },
    { "bench_re_0375", R("[a-z]{4,6}[0-9]{4}"), 0, BENCH_LEN_LAST, BENCH_FEATURE_LAST },
    { "bench_re_0376", R("([abc]{1,4}|[0-9]{1,4})"), 0, BENCH_LEN_LAST, BENCH_FEATURE_LAST },
    { "bench_re_0377", R("([a-z]+[-_])?[0-9]{2,6}"), 0, BENCH_LEN_LAST, BENCH_FEATURE_LAST },
    { "bench_re_0378", R("([A-Z][a-z]{3,5})[.]?"), 0, BENCH_LEN_LAST, BENCH_FEATURE_LAST },
    { "bench_re_0379", R("([a-z]{4}[0-9]?)+"), 0, BENCH_LEN_LAST, BENCH_FEATURE_LAST },
    { "bench_re_0380", R("[a-z]{1,5}[0-9]{1}"), 0, BENCH_LEN_LAST, BENCH_FEATURE_LAST },
    { "bench_re_0381", R("([abc]{2,4}|[0-9]{2,4})"), 0, BENCH_LEN_LAST, BENCH_FEATURE_LAST },
    { "bench_re_0382", R("([a-z]+[-_])?[0-9]{3,6}"), 0, BENCH_LEN_LAST, BENCH_FEATURE_LAST },
    { "bench_re_0383", R("([A-Z][a-z]{4,8})[.]?"), 0, BENCH_LEN_LAST, BENCH_FEATURE_LAST },
    { "bench_re_0384", R("([a-z]{1}[0-9]?)+"), 0, BENCH_LEN_LAST, BENCH_FEATURE_LAST },
    { "bench_re_0385", R("[a-z]{2,5}[0-9]{2}"), 0, BENCH_LEN_LAST, BENCH_FEATURE_LAST },
    { "bench_re_0386", R("([abc]{3,7}|[0-9]{3,7})"), 0, BENCH_LEN_LAST, BENCH_FEATURE_LAST },
    { "bench_re_0387", R("([a-z]+[-_])?[0-9]{4,6}"), 0, BENCH_LEN_LAST, BENCH_FEATURE_LAST },
    { "bench_re_0388", R("([A-Z][a-z]{1,4})[.]?"), 0, BENCH_LEN_LAST, BENCH_FEATURE_LAST },
    { "bench_re_0389", R("([a-z]{2}[0-9]?)+"), 0, BENCH_LEN_LAST, BENCH_FEATURE_LAST },
    { "bench_re_0390", R("[a-z]{3,5}[0-9]{3}"), 0, BENCH_LEN_LAST, BENCH_FEATURE_LAST },
    { "bench_re_0391", R("([abc]{4,7}|[0-9]{4,7})"), 0, BENCH_LEN_LAST, BENCH_FEATURE_LAST },
    { "bench_re_0392", R("([a-z]+[-_])?[0-9]{1,5}"), 0, BENCH_LEN_LAST, BENCH_FEATURE_LAST },
    { "bench_re_0393", R("([A-Z][a-z]{2,4})[.]?"), 0, BENCH_LEN_LAST, BENCH_FEATURE_LAST },
    { "bench_re_0394", R("([a-z]{3}[0-9]?)+"), 0, BENCH_LEN_LAST, BENCH_FEATURE_LAST },
    { "bench_re_0395", R("[a-z]{4,8}[0-9]{4}"), 0, BENCH_LEN_LAST, BENCH_FEATURE_LAST },
    { "bench_re_0396", R("([abc]{1,3}|[0-9]{1,3})"), 0, BENCH_LEN_LAST, BENCH_FEATURE_LAST },
    { "bench_re_0397", R("([a-z]+[-_])?[0-9]{2,5}"), 0, BENCH_LEN_LAST, BENCH_FEATURE_LAST },
    { "bench_re_0398", R("([A-Z][a-z]{3,7})[.]?"), 0, BENCH_LEN_LAST, BENCH_FEATURE_LAST },
    { "bench_re_0399", R("([a-z]{4}[0-9]?)+"), 0, BENCH_LEN_LAST, BENCH_FEATURE_LAST },
    { "bench_re_0400", R("^(cat|dog)[[:space:]]+[0-9]{1,4}$"), 0, BENCH_LEN_LAST, BENCH_FEATURE_LAST },
    { "bench_re_0401", R("\\b(dog|bird|[a-z]{2,4})[-_]?[0-9]*\\b"), 0, BENCH_LEN_LAST, BENCH_FEATURE_LAST },
    { "bench_re_0402", R("([a-z]{3,5}|[0-9]{3,5})+end?"), 0, BENCH_LEN_LAST, BENCH_FEATURE_LAST },
    { "bench_re_0403", R("^([A-Za-z]{1,5}[.]?)+$"), 0, BENCH_LEN_LAST, BENCH_FEATURE_LAST },
    { "bench_re_0404", R("([a-z]+:)?//([a-z0-9.-]+)(/[a-z0-9._-]*)?"), 0, BENCH_LEN_LAST, BENCH_FEATURE_LAST },
    { "bench_re_0405", R("^(cat|dog)[[:space:]]+[0-9]{3,6}$"), 0, BENCH_LEN_LAST, BENCH_FEATURE_LAST },
    { "bench_re_0406", R("\\b(dog|bird|[a-z]{1,3})[-_]?[0-9]*\\b"), 0, BENCH_LEN_LAST, BENCH_FEATURE_LAST },
    { "bench_re_0407", R("([a-z]{2,4}|[0-9]{2,4})+end?"), 0, BENCH_LEN_LAST, BENCH_FEATURE_LAST },
    { "bench_re_0408", R("^([A-Za-z]{3,7}[.]?)+$"), 0, BENCH_LEN_LAST, BENCH_FEATURE_LAST },
    { "bench_re_0409", R("([a-z]+:)?//([a-z0-9.-]+)(/[a-z0-9._-]*)?"), 0, BENCH_LEN_LAST, BENCH_FEATURE_LAST },
    { "bench_re_0410", R("^(cat|dog)[[:space:]]+[0-9]{2,5}$"), 0, BENCH_LEN_LAST, BENCH_FEATURE_LAST },
    { "bench_re_0411", R("\\b(dog|bird|[a-z]{3,5})[-_]?[0-9]*\\b"), 0, BENCH_LEN_LAST, BENCH_FEATURE_LAST },
    { "bench_re_0412", R("([a-z]{1,3}|[0-9]{1,3})+end?"), 0, BENCH_LEN_LAST, BENCH_FEATURE_LAST },
    { "bench_re_0413", R("^([A-Za-z]{2,6}[.]?)+$"), 0, BENCH_LEN_LAST, BENCH_FEATURE_LAST },
    { "bench_re_0414", R("([a-z]+:)?//([a-z0-9.-]+)(/[a-z0-9._-]*)?"), 0, BENCH_LEN_LAST, BENCH_FEATURE_LAST },
    { "bench_re_0415", R("^(cat|dog)[[:space:]]+[0-9]{1,4}$"), 0, BENCH_LEN_LAST, BENCH_FEATURE_LAST },
    { "bench_re_0416", R("\\b(dog|bird|[a-z]{2,4})[-_]?[0-9]*\\b"), 0, BENCH_LEN_LAST, BENCH_FEATURE_LAST },
    { "bench_re_0417", R("([a-z]{3,5}|[0-9]{3,5})+end?"), 0, BENCH_LEN_LAST, BENCH_FEATURE_LAST },
    { "bench_re_0418", R("^([A-Za-z]{1,5}[.]?)+$"), 0, BENCH_LEN_LAST, BENCH_FEATURE_LAST },
    { "bench_re_0419", R("([a-z]+:)?//([a-z0-9.-]+)(/[a-z0-9._-]*)?"), 0, BENCH_LEN_LAST, BENCH_FEATURE_LAST },
    { "bench_re_0420", R("^(cat|dog)[[:space:]]+[0-9]{3,6}$"), 0, BENCH_LEN_LAST, BENCH_FEATURE_LAST },
    { "bench_re_0421", R("\\b(dog|bird|[a-z]{1,3})[-_]?[0-9]*\\b"), 0, BENCH_LEN_LAST, BENCH_FEATURE_LAST },
    { "bench_re_0422", R("([a-z]{2,4}|[0-9]{2,4})+end?"), 0, BENCH_LEN_LAST, BENCH_FEATURE_LAST },
    { "bench_re_0423", R("^([A-Za-z]{3,7}[.]?)+$"), 0, BENCH_LEN_LAST, BENCH_FEATURE_LAST },
    { "bench_re_0424", R("([a-z]+:)?//([a-z0-9.-]+)(/[a-z0-9._-]*)?"), 0, BENCH_LEN_LAST, BENCH_FEATURE_LAST },
    { "bench_re_0425", R("^(cat|dog)[[:space:]]+[0-9]{2,5}$"), 0, BENCH_LEN_LAST, BENCH_FEATURE_LAST },
    { "bench_re_0426", R("\\b(dog|bird|[a-z]{3,5})[-_]?[0-9]*\\b"), 0, BENCH_LEN_LAST, BENCH_FEATURE_LAST },
    { "bench_re_0427", R("([a-z]{1,3}|[0-9]{1,3})+end?"), 0, BENCH_LEN_LAST, BENCH_FEATURE_LAST },
    { "bench_re_0428", R("^([A-Za-z]{2,6}[.]?)+$"), 0, BENCH_LEN_LAST, BENCH_FEATURE_LAST },
    { "bench_re_0429", R("([a-z]+:)?//([a-z0-9.-]+)(/[a-z0-9._-]*)?"), 0, BENCH_LEN_LAST, BENCH_FEATURE_LAST },
    { "bench_re_0430", R("^(cat|dog)[[:space:]]+[0-9]{1,4}$"), 0, BENCH_LEN_LAST, BENCH_FEATURE_LAST },
    { "bench_re_0431", R("\\b(dog|bird|[a-z]{2,4})[-_]?[0-9]*\\b"), 0, BENCH_LEN_LAST, BENCH_FEATURE_LAST },
    { "bench_re_0432", R("([a-z]{3,5}|[0-9]{3,5})+end?"), 0, BENCH_LEN_LAST, BENCH_FEATURE_LAST },
    { "bench_re_0433", R("^([A-Za-z]{1,5}[.]?)+$"), 0, BENCH_LEN_LAST, BENCH_FEATURE_LAST },
    { "bench_re_0434", R("([a-z]+:)?//([a-z0-9.-]+)(/[a-z0-9._-]*)?"), 0, BENCH_LEN_LAST, BENCH_FEATURE_LAST },
    { "bench_re_0435", R("^(cat|dog)[[:space:]]+[0-9]{3,6}$"), 0, BENCH_LEN_LAST, BENCH_FEATURE_LAST },
    { "bench_re_0436", R("\\b(dog|bird|[a-z]{1,3})[-_]?[0-9]*\\b"), 0, BENCH_LEN_LAST, BENCH_FEATURE_LAST },
    { "bench_re_0437", R("([a-z]{2,4}|[0-9]{2,4})+end?"), 0, BENCH_LEN_LAST, BENCH_FEATURE_LAST },
    { "bench_re_0438", R("^([A-Za-z]{3,7}[.]?)+$"), 0, BENCH_LEN_LAST, BENCH_FEATURE_LAST },
    { "bench_re_0439", R("([a-z]+:)?//([a-z0-9.-]+)(/[a-z0-9._-]*)?"), 0, BENCH_LEN_LAST, BENCH_FEATURE_LAST },
    { "bench_re_0440", R("^(cat|dog)[[:space:]]+[0-9]{2,5}$"), 0, BENCH_LEN_LAST, BENCH_FEATURE_LAST },
    { "bench_re_0441", R("\\b(dog|bird|[a-z]{3,5})[-_]?[0-9]*\\b"), 0, BENCH_LEN_LAST, BENCH_FEATURE_LAST },
    { "bench_re_0442", R("([a-z]{1,3}|[0-9]{1,3})+end?"), 0, BENCH_LEN_LAST, BENCH_FEATURE_LAST },
    { "bench_re_0443", R("^([A-Za-z]{2,6}[.]?)+$"), 0, BENCH_LEN_LAST, BENCH_FEATURE_LAST },
    { "bench_re_0444", R("([a-z]+:)?//([a-z0-9.-]+)(/[a-z0-9._-]*)?"), 0, BENCH_LEN_LAST, BENCH_FEATURE_LAST },
    { "bench_re_0445", R("^(cat|dog)[[:space:]]+[0-9]{1,4}$"), 0, BENCH_LEN_LAST, BENCH_FEATURE_LAST },
    { "bench_re_0446", R("\\b(dog|bird|[a-z]{2,4})[-_]?[0-9]*\\b"), 0, BENCH_LEN_LAST, BENCH_FEATURE_LAST },
    { "bench_re_0447", R("([a-z]{3,5}|[0-9]{3,5})+end?"), 0, BENCH_LEN_LAST, BENCH_FEATURE_LAST },
    { "bench_re_0448", R("^([A-Za-z]{1,5}[.]?)+$"), 0, BENCH_LEN_LAST, BENCH_FEATURE_LAST },
    { "bench_re_0449", R("([a-z]+:)?//([a-z0-9.-]+)(/[a-z0-9._-]*)?"), 0, BENCH_LEN_LAST, BENCH_FEATURE_LAST },
    { "bench_re_0450", R("^(cat|dog)[[:space:]]+[0-9]{3,6}$"), 0, BENCH_LEN_LAST, BENCH_FEATURE_LAST },
    { "bench_re_0451", R("\\b(dog|bird|[a-z]{1,3})[-_]?[0-9]*\\b"), 0, BENCH_LEN_LAST, BENCH_FEATURE_LAST },
    { "bench_re_0452", R("([a-z]{2,4}|[0-9]{2,4})+end?"), 0, BENCH_LEN_LAST, BENCH_FEATURE_LAST },
    { "bench_re_0453", R("^([A-Za-z]{3,7}[.]?)+$"), 0, BENCH_LEN_LAST, BENCH_FEATURE_LAST },
    { "bench_re_0454", R("([a-z]+:)?//([a-z0-9.-]+)(/[a-z0-9._-]*)?"), 0, BENCH_LEN_LAST, BENCH_FEATURE_LAST },
    { "bench_re_0455", R("^(cat|dog)[[:space:]]+[0-9]{2,5}$"), 0, BENCH_LEN_LAST, BENCH_FEATURE_LAST },
    { "bench_re_0456", R("\\b(dog|bird|[a-z]{3,5})[-_]?[0-9]*\\b"), 0, BENCH_LEN_LAST, BENCH_FEATURE_LAST },
    { "bench_re_0457", R("([a-z]{1,3}|[0-9]{1,3})+end?"), 0, BENCH_LEN_LAST, BENCH_FEATURE_LAST },
    { "bench_re_0458", R("^([A-Za-z]{2,6}[.]?)+$"), 0, BENCH_LEN_LAST, BENCH_FEATURE_LAST },
    { "bench_re_0459", R("([a-z]+:)?//([a-z0-9.-]+)(/[a-z0-9._-]*)?"), 0, BENCH_LEN_LAST, BENCH_FEATURE_LAST },
    { "bench_re_0460", R("^(cat|dog)[[:space:]]+[0-9]{1,4}$"), 0, BENCH_LEN_LAST, BENCH_FEATURE_LAST },
    { "bench_re_0461", R("\\b(dog|bird|[a-z]{2,4})[-_]?[0-9]*\\b"), 0, BENCH_LEN_LAST, BENCH_FEATURE_LAST },
    { "bench_re_0462", R("([a-z]{3,5}|[0-9]{3,5})+end?"), 0, BENCH_LEN_LAST, BENCH_FEATURE_LAST },
    { "bench_re_0463", R("^([A-Za-z]{1,5}[.]?)+$"), 0, BENCH_LEN_LAST, BENCH_FEATURE_LAST },
    { "bench_re_0464", R("([a-z]+:)?//([a-z0-9.-]+)(/[a-z0-9._-]*)?"), 0, BENCH_LEN_LAST, BENCH_FEATURE_LAST },
    { "bench_re_0465", R("^(cat|dog)[[:space:]]+[0-9]{3,6}$"), 0, BENCH_LEN_LAST, BENCH_FEATURE_LAST },
    { "bench_re_0466", R("\\b(dog|bird|[a-z]{1,3})[-_]?[0-9]*\\b"), 0, BENCH_LEN_LAST, BENCH_FEATURE_LAST },
    { "bench_re_0467", R("([a-z]{2,4}|[0-9]{2,4})+end?"), 0, BENCH_LEN_LAST, BENCH_FEATURE_LAST },
    { "bench_re_0468", R("^([A-Za-z]{3,7}[.]?)+$"), 0, BENCH_LEN_LAST, BENCH_FEATURE_LAST },
    { "bench_re_0469", R("([a-z]+:)?//([a-z0-9.-]+)(/[a-z0-9._-]*)?"), 0, BENCH_LEN_LAST, BENCH_FEATURE_LAST },
    { "bench_re_0470", R("^(cat|dog)[[:space:]]+[0-9]{2,5}$"), 0, BENCH_LEN_LAST, BENCH_FEATURE_LAST },
    { "bench_re_0471", R("\\b(dog|bird|[a-z]{3,5})[-_]?[0-9]*\\b"), 0, BENCH_LEN_LAST, BENCH_FEATURE_LAST },
    { "bench_re_0472", R("([a-z]{1,3}|[0-9]{1,3})+end?"), 0, BENCH_LEN_LAST, BENCH_FEATURE_LAST },
    { "bench_re_0473", R("^([A-Za-z]{2,6}[.]?)+$"), 0, BENCH_LEN_LAST, BENCH_FEATURE_LAST },
    { "bench_re_0474", R("([a-z]+:)?//([a-z0-9.-]+)(/[a-z0-9._-]*)?"), 0, BENCH_LEN_LAST, BENCH_FEATURE_LAST },
    { "bench_re_0475", R("^(cat|dog)[[:space:]]+[0-9]{1,4}$"), 0, BENCH_LEN_LAST, BENCH_FEATURE_LAST },
    { "bench_re_0476", R("\\b(dog|bird|[a-z]{2,4})[-_]?[0-9]*\\b"), 0, BENCH_LEN_LAST, BENCH_FEATURE_LAST },
    { "bench_re_0477", R("([a-z]{3,5}|[0-9]{3,5})+end?"), 0, BENCH_LEN_LAST, BENCH_FEATURE_LAST },
    { "bench_re_0478", R("^([A-Za-z]{1,5}[.]?)+$"), 0, BENCH_LEN_LAST, BENCH_FEATURE_LAST },
    { "bench_re_0479", R("([a-z]+:)?//([a-z0-9.-]+)(/[a-z0-9._-]*)?"), 0, BENCH_LEN_LAST, BENCH_FEATURE_LAST },
    { "bench_re_0480", R("^(cat|dog)[[:space:]]+[0-9]{3,6}$"), 0, BENCH_LEN_LAST, BENCH_FEATURE_LAST },
    { "bench_re_0481", R("\\b(dog|bird|[a-z]{1,3})[-_]?[0-9]*\\b"), 0, BENCH_LEN_LAST, BENCH_FEATURE_LAST },
    { "bench_re_0482", R("([a-z]{2,4}|[0-9]{2,4})+end?"), 0, BENCH_LEN_LAST, BENCH_FEATURE_LAST },
    { "bench_re_0483", R("^([A-Za-z]{3,7}[.]?)+$"), 0, BENCH_LEN_LAST, BENCH_FEATURE_LAST },
    { "bench_re_0484", R("([a-z]+:)?//([a-z0-9.-]+)(/[a-z0-9._-]*)?"), 0, BENCH_LEN_LAST, BENCH_FEATURE_LAST },
    { "bench_re_0485", R("^(cat|dog)[[:space:]]+[0-9]{2,5}$"), 0, BENCH_LEN_LAST, BENCH_FEATURE_LAST },
    { "bench_re_0486", R("\\b(dog|bird|[a-z]{3,5})[-_]?[0-9]*\\b"), 0, BENCH_LEN_LAST, BENCH_FEATURE_LAST },
    { "bench_re_0487", R("([a-z]{1,3}|[0-9]{1,3})+end?"), 0, BENCH_LEN_LAST, BENCH_FEATURE_LAST },
    { "bench_re_0488", R("^([A-Za-z]{2,6}[.]?)+$"), 0, BENCH_LEN_LAST, BENCH_FEATURE_LAST },
    { "bench_re_0489", R("([a-z]+:)?//([a-z0-9.-]+)(/[a-z0-9._-]*)?"), 0, BENCH_LEN_LAST, BENCH_FEATURE_LAST },
    { "bench_re_0490", R("^(cat|dog)[[:space:]]+[0-9]{1,4}$"), 0, BENCH_LEN_LAST, BENCH_FEATURE_LAST },
    { "bench_re_0491", R("\\b(dog|bird|[a-z]{2,4})[-_]?[0-9]*\\b"), 0, BENCH_LEN_LAST, BENCH_FEATURE_LAST },
    { "bench_re_0492", R("([a-z]{3,5}|[0-9]{3,5})+end?"), 0, BENCH_LEN_LAST, BENCH_FEATURE_LAST },
    { "bench_re_0493", R("^([A-Za-z]{1,5}[.]?)+$"), 0, BENCH_LEN_LAST, BENCH_FEATURE_LAST },
    { "bench_re_0494", R("([a-z]+:)?//([a-z0-9.-]+)(/[a-z0-9._-]*)?"), 0, BENCH_LEN_LAST, BENCH_FEATURE_LAST },
    { "bench_re_0495", R("^(cat|dog)[[:space:]]+[0-9]{3,6}$"), 0, BENCH_LEN_LAST, BENCH_FEATURE_LAST },
    { "bench_re_0496", R("\\b(dog|bird|[a-z]{1,3})[-_]?[0-9]*\\b"), 0, BENCH_LEN_LAST, BENCH_FEATURE_LAST },
    { "bench_re_0497", R("([a-z]{2,4}|[0-9]{2,4})+end?"), 0, BENCH_LEN_LAST, BENCH_FEATURE_LAST },
    { "bench_re_0498", R("^([A-Za-z]{3,7}[.]?)+$"), 0, BENCH_LEN_LAST, BENCH_FEATURE_LAST },
    { "bench_re_0499", R("([a-z]+:)?//([a-z0-9.-]+)(/[a-z0-9._-]*)?"), 0, BENCH_LEN_LAST, BENCH_FEATURE_LAST },
};

#endif /* META_BENCH_REGEXES_H */
