#if !defined(META_TESTS_ARRAY_H)
#define META_TESTS_ARRAY_H

#include "meta_tests.h"

static RegexTest regex_tests[] = {
    {"abc5def",      R("[0-9]")},
    {"hello world",  R("[0-9]")},
    {"2hello world", R("^[0-9]")},
    {"hello 2",      R("^[0-9]")},
    {"test end5",    R("[0-9]$")},
    {"test 5end",    R("[0-9]$")},
    {"a.c",          R("a.c")},
    {"abc",          R("a.c")},
    {"abc",          R("^abc$")},
    {"abcd",         R("^abc$")},
    {"HELLO",        R("[A-Z]")},
    {"hello",        R("[A-Z]")},
    {"abc XYZ 123",  R("[a-z]")},
    {"123 XYZ",      R("[a-z]")},
    {"foo (bar)",    R("\\([a-z]+\\)")},
    {"foo bar",      R("(foo) (bar)")},
    {"a1b2",         R("([a-z])([0-9])")},
    {"nested",       R("n(e(s)t)ed")},
    {"abbbc",        R("ab*c")},
    {"ac",           R("ab*c")},
    {"ac",           R("ab+c")},
    {"abc",          R("ab+c")},
    {"abc",          R("ab?c")},
    {"ac",           R("ab?c")},
    {"abbc",         R("ab?c")},
    {"a123b",        R("a[0-9]+b")},
    {"aXXXb",        R("a.+b")},
    {"ab",           R("a.*b")},
    {"a",            R("a|b")},
    {"b",            R("a|b")},
    {"c",            R("a|b")},
    {"foo",          R("foo|bar")},
    {"bar",          R("foo|bar")},
    {"baz",          R("foo|bar")},
    {"abc",          R("a(b|c|d)c")},
    {"acc",          R("a(b|c|d)c")},
    {"adc",          R("a(b|c|d)c")},
    {"aec",          R("a(b|c|d)c")},
    {"123 foo",      R("([0-9]+) (foo|bar)")},
    {"456 bar",      R("([0-9]+) (foo|bar)")},
    {"789 baz",      R("([0-9]+) (foo|bar)")},
    {"a",            R("[abc]")},
    {"é",            R("é")},
    {"é",            R("[é]")},
    {"e",            R("^é$")},
    {"d",            R("[abc]")},
    {"x",            R("[^abc]")},
    {"a",            R("[^abc]")},
    {"foo123bar",    R("[0-9]+")},
    {"A",            R("[a-zA-Z]")},
    {"-",            R("[-abc]")},
    {"-",            R("[abc-]")},
    {"]",            R("[]abc]")},
    {"a",            R("[]abc]")},
    {"]",            R("[^]abc]")},
    {"x",            R("[^]abc]")},
    {"a{3}b",        R("a\\{3\\}b")},
    {"aaab",         R("a{3}b")},
    {"aab",          R("a{3}b")},
    {"aaaab",        R("a{3}b")},
    {"aab",          R("a{2,4}b")},
    {"aaab",         R("a{2,4}b")},
    {"aaaab",        R("a{2,4}b")},
    {"aaaaab",       R("a{2,4}b")},
    {"ab",           R("a{2,4}b")},
    {"aab",          R("a{2,}b")},
    {"aaaaaaab",     R("a{2,}b")},
    {"ab",           R("a{2,}b")},
    {"123a",         R("[[:digit:]]+")},
    {"123",          R("^[[:digit:]]+$")},
    {"abc",          R("^[[:alpha:]]+$")},
    {"a1B",          R("^[[:alnum:]]+$")},
    {" \t\n",        R("^[[:space:]]+$")},
    {"a B",          R("^[[:lower:]][[:space:]][[:upper:]]$")},
    {"a1 B",         R("^[[:lower:][:digit:]]+[[:space:]][[:upper:]]$")},
    {"!@#$%&*()-+=", R("^[[:punct:]]+$")},
    {" ",            R("^[^[:alnum:][:punct:]]$")},
    {"😀",           R("a")},
    {"😀",           R("😀")},
    {"👪",           R("👪")},
    {"🇩🇪",         R("🇩🇪")},
    {"🇩🇪",         R("🇩")},
    {"🇩🇪",         R("a")},
};

#endif /* META_TESTS_ARRAY_H */
