name: Test on various platforms CI

on:
  push:
    branches:
  pull_request:

jobs:
  macos:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install build deps
        run: |
          xcode-select --install 2>/dev/null || true
          cc --version

      - name: Build and Test
        run: ./build.sh test

  ubuntu:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install build deps
        run: cc --version

      - name: Build and Test
        run: ./build.sh test

  windows-msvc:
    runs-on: windows-latest
    env:
      MSYS2_ARG_CONV_EXCL: "*"
    defaults:
      run:
        shell: bash
    steps:
      - uses: actions/checkout@v4

      - name: Setup MSVC environment
        uses: ilammy/msvc-dev-cmd@v1

      - name: Build standalone with clang-cl
        run: |
          clang-cl --version
          CFLAGS=-fuse-ld=lld CC=clang-cl ./build.sh standalone

  bsd:
    runs-on: ubuntu-latest
    name: ${{ matrix.name }} VM
    timeout-minutes: 25
    defaults:
      run:
        shell: cpa.sh {0} --sync-files runner-to-vm
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: FreeBSD
            os: freebsd
            version: "15.1"
          - name: OpenBSD
            os: openbsd
            version: "7.9"
          - name: NetBSD
            os: netbsd
            version: "11.0"
    steps:
      - uses: actions/checkout@v4

      - name: Start VM
        uses: cross-platform-actions/action@v1.4.0
        with:
          operating_system: ${{ matrix.os }}
          version: ${{ matrix.version }}
          shell: sh
          memory: 4G
          cpu_count: 2

      - name: Build and Test
        run: |
          cc --version
          ./build.sh test
